version: "3.2"

services:
 nginx:
   image: nginx:alpine
   volumes:
     - .:/var/www
     - ./nginx/conf.d/:/etc/nginx/conf.d/
   ports:
     - 80:80
     - 443:443
   depends_on:
     - php

 php:
   build:
     context: .
   volumes:
     - .:/var/www
   ports:
     - 9000:9000
