version: "3.2"

services:
 nginx:
   image: nginx:alpine
   volumes:
     - ./var/www:/var/www
     - ./nginx/conf.d/:/etc/nginx/conf.d/
   ports:
     - 80:80
     - 444:444
   depends_on:
     - php

 php:
   build:
     context: .
   volumes:
     - ./var/www:/var/www
   ports:
     - 9001:9001
